### ISSUE TITLE
Create randomizer logic for seed generation

### ISSUE THREAD

**Issue by minous27** [minous27/TheMessengerRandomizerMod#6]
- Will prevent unbeatable seeds from being created. Greatly increases use.
- Will want to design a system that can be fed "randomizer rules", allowing for easy manipulation
- Effort size - VapeNation

**Comment by kriogenic** [comment]
Two of the largest improvements I have found to make a larger percent of seeds completed has been to add an option to have the grapple hook spawn in one of 2 easy access early locations wingsuit or magic boots which opens up a lot of other areas. The other has been to change it so that the magic boots can not spawn at the key of chaos or sun and moon crest locations which in most cases resulted in unbeatable seeds.

**Comment by minous27** [comment]
Those are good thoughts there for quick changes to the randomizer to make them more beatable. In current OoB strats, I've actually been told there really isn't an unbeatable seed out there anymore. Of course that only applies to the more veteran runners of the game. Casual players will find the seeds unbeatable. 

I am currently working on the system now that can make these kinds of logical checks when generating mappings. There is actually a diagram of it in the project. Feel free to take a look and let me know if you see any issues with that logic flow.

**Comment by kriogenic** [comment]
The logic looks pretty good in the diagram. If thats what you are working on then I will wait for the next update.

I've randomized the shop prices and I am currently working on getting the award item text to show the randomized item instead of the original. I am not very good with GIT but maybe if you want a hand on somethings we can chat on discord? I am in the Sabotage Studio server if you want to find me.
